export interface IReport {
  proName: string
  proCode: string
  keyMark: string
  energysavingMark: string
  startDate: string
  productDate: string
  plantotalInvest: number
  stotalInvest: number
  ytotalInvest: number
  construction: number
  installation: number
  toolsPurchase: number
  otherCost: number
  constructionArea: number
  houseCon: number
  completesArea: number
  houseCom: number
  houseTotalInvest: number
  houseComInvest: number
  newFixedAsset: number
  productiveAsset: number
  noproductiveInvest: number
  incompleteInvest: number
  abilityCode: string
  countUnit: string
  designAbility: string
  yearSize: string
  cumIncrease: string
  yearIncrease: string
  doneOtherWork: string
  imageProgress: string
  proNumber: string
  increaseProduction: number
  energySaving: number
  otherSaving: number
  addBreed: number
  increaseQuality: number
  sfzl: number
  others: number
  fundSource: string
  recordDate: string
  yplanInvest: number
  nlym: number
  syys: number
  qt: number
  gyjz: number
  zz: number
}
